services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: quanlynhansu
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/quanlynhansu
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: thnhpahm2710